create table film (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo varchar(256),
    riassunto varchar(1024)
);

insert into film (id, titolo, riassunto)
values 
(default, 'Imitation Game',  'The Imitation Game è un film del 2014 
diretto da Morten Tyldum, con protagonista Benedict Cumberbatch nei panni del 
matematico e crittoanalista Alan Turing. La pellicola è l''adattamento 
cinematografico della biografia Alan Turing. Una biografia (Alan Turing: 
The Enigma), pubblicata dopo l''uscita del film anche col titolo Alan Turing. 
Storia di un enigma, scritta da Andrew Hodges[1] nel 1983.'),

(default, 'Titanic', 'Titanic è un film colossal del 1997 scritto, 
diretto e co-montato da James Cameron, con protagonisti Leonardo DiCaprio 
e Kate Winslet nei ruoli di Jack e Rose, membri di differenti classi sociali 
che s''innamorano durante il tragico viaggio inaugurale del RMS Titanic.

È, ad oggi, il secondo film con il maggiore incasso nella 
storia mondiale del cinema (il primo è Avatar (2009), sempre diretto 
da Cameron), nonché uno dei film a detenere il record di più nomination 
agli Oscar (14 candidature) ed uno di quelli con più vittorie in assoluto 
della prestigiosa statuetta d''oro (11 vittorie ai Premi Oscar 1998), insieme 
a Il Signore degli Anelli - Il ritorno del re e Ben-Hur.)'),

(default, 'Armageddon', 'Armageddon - Giudizio finale (Armageddon) è un film 
del 1998 diretto da Michael Bay. Negli Stati uniti uscì il 1 luglio del 1998, 
mentre nelle sale Italiane arrivò il 4 settembre dello stesso anno.');

select * from users where user= ? and password = ?